# Generated by Django 3.0.4 on 2021-02-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibits_name', models.CharField(max_length=50)),
                ('exhibits_type', models.CharField(choices=[('Painting', 'painting'), ('Sculpture', 'sculpture')], max_length=15)),
                ('style', models.CharField(choices=[('Realism', 'realism')], max_length=15)),
                ('creations_year', models.DateField()),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('exhibitions_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exhibits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Exhibit')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='masters_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Master'),
        ),
    ]
