# Generated by Django 3.0.4 on 2021-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibits_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=15),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='style',
            field=models.CharField(choices=[('realism', 'Realism')], max_length=15),
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibits',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibits',
            field=models.ManyToManyField(to='gallery.Exhibit'),
        ),
    ]
