# Generated by Django 3.0.4 on 2020-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0002_auto_20201209_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
