# Generated by Django 3.0.4 on 2020-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0003_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(default='none.jpg', upload_to='trpo'),
        ),
    ]
