# Generated by Django 3.0.4 on 2020-12-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0004_auto_20201216_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(default='black.png', upload_to='trpo'),
        ),
    ]
