# Generated by Django 3.0.4 on 2020-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0005_auto_20201217_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(default='templates/trpo/img/none.png', upload_to='trpo'),
        ),
    ]
