# Generated by Django 3.0.4 on 2020-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0006_auto_20201217_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('category',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Помощь', 'verbose_name_plural': 'Помощь'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главные'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='trpo'),
        ),
    ]
