# Generated by Django 3.0.4 on 2020-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0007_auto_20201217_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
    ]
