# Generated by Django 3.0.4 on 2020-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0009_auto_20201217_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='trpo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='help',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='help',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='help',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='help',
            name='telephon',
            field=models.CharField(max_length=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='index',
            name='about',
            field=models.TextField(verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='index',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='trpo.Goods', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephon',
            field=models.CharField(max_length=10, verbose_name='Телефон'),
        ),
    ]
