# Generated by Django 3.0.4 on 2020-12-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0010_auto_20201217_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='code',
        ),
    ]
