# Generated by Django 3.0.4 on 2020-12-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0011_remove_goods_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('category', 'id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
