# Generated by Django 3.0.4 on 2020-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpo', '0012_auto_20201217_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='about_product',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='trpo'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='help',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='help',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='help',
            name='telephon',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='trpo.Goods'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephon',
            field=models.CharField(max_length=13),
        ),
    ]
