# Generated by Django 3.0.4 on 2020-12-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Positions_Name', models.CharField(max_length=50)),
                ('Rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('achievements', models.IntegerField(default=0)),
                ('contract', models.IntegerField(default=0)),
                ('time_days', models.IntegerField(default=23)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_young', models.IntegerField()),
                ('count_old', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.People')),
            ],
        ),
    ]
