# Generated by Django 3.0.4 on 2020-12-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='CH_count',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='FSZN',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='TS',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='UF',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='accrued',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='tax',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='salary',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='Rate',
            field=models.FloatField(default=0),
        ),
    ]
