# Generated by Django 3.0.4 on 2020-12-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_auto_20201207_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='position',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
