# Generated by Django 3.0.4 on 2020-12-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_auto_20201207_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('count_young', models.IntegerField()),
                ('count_old', models.IntegerField()),
                ('experience', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('achievements', models.IntegerField(default=0)),
                ('contract', models.IntegerField(default=0)),
                ('time_days', models.IntegerField(default=23)),
                ('salary', models.FloatField(blank=True, default=0)),
                ('TS', models.FloatField(blank=True, default=0)),
                ('accrued', models.FloatField(blank=True, default=0)),
                ('CH_count', models.FloatField(blank=True, default=0)),
                ('UF', models.FloatField(blank=True, default=0)),
                ('FSZN', models.FloatField(blank=True, default=0)),
                ('tax', models.FloatField(blank=True, default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.Position')),
            ],
        ),
    ]
