# Generated by Django 3.0.4 on 2020-12-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0005_auto_20201207_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='count_old',
        ),
    ]
