# Generated by Django 3.0.4 on 2020-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0006_remove_people_count_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='accrued',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
