# Generated by Django 3.0.4 on 2020-12-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0007_people_accrued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должности', 'verbose_name_plural': 'Должность'},
        ),
        migrations.AlterField(
            model_name='people',
            name='accrued',
            field=models.IntegerField(blank=True, default=0, verbose_name='Начисленно'),
        ),
        migrations.AlterField(
            model_name='people',
            name='achievements',
            field=models.IntegerField(default=0, verbose_name='Процент за достижения'),
        ),
        migrations.AlterField(
            model_name='people',
            name='contract',
            field=models.IntegerField(default=0, verbose_name='Процент по контракту'),
        ),
        migrations.AlterField(
            model_name='people',
            name='count_young',
            field=models.IntegerField(default=0, verbose_name='Количество детей до 18 лет'),
        ),
        migrations.AlterField(
            model_name='people',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Процент стажа'),
        ),
        migrations.AlterField(
            model_name='people',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='people',
            name='prize',
            field=models.IntegerField(default=0, verbose_name='Процент премии'),
        ),
        migrations.AlterField(
            model_name='people',
            name='salary',
            field=models.FloatField(blank=True, default=0, verbose_name='Карт-счет'),
        ),
        migrations.AlterField(
            model_name='people',
            name='time_days',
            field=models.IntegerField(default=23, verbose_name='Количество проработанных дней'),
        ),
        migrations.AlterField(
            model_name='position',
            name='Positions_Name',
            field=models.CharField(max_length=50, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='position',
            name='Rate',
            field=models.FloatField(default=0, verbose_name='Разряд'),
        ),
    ]
