# Generated by Django 3.0.4 on 2020-12-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0008_auto_20201218_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
            ],
        ),
    ]
