# Generated by Django 3.0.4 on 2020-12-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0009_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
